### ISSUE TITLE
Doesn't work on OPNsense

### ISSUE THREAD

**Issue by SurinameClubcard** [eborisch/ethname#2]
Referring to https://github.com/opnsense/tools/issues/202, I just wanted to say that I am not able to get this working on OPNsense 22.1.10. It did work on a setup with two NICs (WAN and LAN), but after adding the third NIC, OPNsense completely didn't understand the assignments for WAN, LAN and OPT1 anymore...

**Comment by eborisch** [comment]
I'm not an OPNsense user, and from what I understand in the ticket you referred to, it may bring up networks in a different/non-standard FreeBSD rc-way.

That said, if there are changes that would make it work (while not breaking FreeBSD) that you would like added, I'm happy to entertain those.

**Comment by eborisch** [comment]
There’s a short thread [here](https://forum.opnsense.org/index.php?topic=27023.0) where users have a configuration that is working well for ethname in OPNsense. I’m happy to take a PR with additional documentation if someone has the time to do that, but I’m closing this issue.
